version: "3.8"

services:
  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/moviesdb --quiet
  choremanagement:
    image: registry.gitlab.com/family_chore_tracker/choremanagement:0.0.1
    container_name: choremanagement
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/moviesdb
